"""Discord send_message implementation and attachment helpers."""

from __future__ import annotations

import io
from urllib.parse import urlparse

import aiohttp
import discord
from daimon.adapters.mcp.auth.resolver import AuthIdentity
from daimon.adapters.mcp.file_store import FileStore
from daimon.adapters.mcp.runtime import McpRuntime
from daimon.adapters.mcp.tools.discord._client import (
    _require_bot_token,  # pyright: ignore[reportPrivateUsage]
    _require_discord_identity,  # pyright: ignore[reportPrivateUsage]
    _require_guild_channel,  # pyright: ignore[reportPrivateUsage]
    _require_guild_id,  # pyright: ignore[reportPrivateUsage]
    _resolve_channel,  # pyright: ignore[reportPrivateUsage]
    _resolve_member,  # pyright: ignore[reportPrivateUsage]
    rest_client,  # pyright: ignore[reportPrivateUsage]
)
from daimon.adapters.mcp.tools.discord._models import (
    MessageRow,
    _to_message_row,  # pyright: ignore[reportPrivateUsage]
)
from daimon.adapters.mcp.tools.discord._visibility import (
    _check_send_permission,  # pyright: ignore[reportPrivateUsage]
    _ensure_thread_parent_cached,  # pyright: ignore[reportPrivateUsage]
)
from fastmcp.exceptions import ToolError

# Discord uses MiB, not MB, for the per-attachment cap.
_DISCORD_ATTACHMENT_MAX_BYTES: int = 25 * 1024 * 1024
_MAX_ATTACHMENTS_PER_MESSAGE: int = 10

# SSRF guard: attachment fetches are restricted to Discord's CDN hosts. A bare
# https scheme check is insufficient — an attacker-supplied https URL can
# open-redirect to an internal target (e.g. the cloud metadata endpoint). We
# allowlist the only hosts Discord serves attachments from and disable redirect
# following so an allowlisted URL cannot bounce elsewhere.
_ALLOWED_ATTACHMENT_HOSTS: frozenset[str] = frozenset(
    {"cdn.discordapp.com", "media.discordapp.net"}
)


async def _fetch_attachment(session: aiohttp.ClientSession, url: str) -> bytes:
    parsed = urlparse(url)
    if parsed.scheme != "https" or (parsed.hostname or "").lower() not in _ALLOWED_ATTACHMENT_HOSTS:
        raise ToolError("attachment url must be an https discord cdn url")
    try:
        async with session.get(url, allow_redirects=False) as resp:
            resp.raise_for_status()
            cl = resp.content_length
            if cl is not None and cl > _DISCORD_ATTACHMENT_MAX_BYTES:
                raise ToolError("attachment exceeds 25 MiB")
            buf = io.BytesIO()
            async for chunk in resp.content.iter_chunked(64 * 1024):
                if buf.tell() + len(chunk) > _DISCORD_ATTACHMENT_MAX_BYTES:
                    raise ToolError("attachment exceeds 25 MiB")
                buf.write(chunk)
            return buf.getvalue()
    except aiohttp.ClientError as exc:
        # Named boundary: any HTTP-fetch failure (raise_for_status, connection
        # reset, timeout) becomes a ToolError instead of escaping to FastMCP as
        # an opaque internal error. The size-limit ToolError above is not an
        # aiohttp.ClientError, so it propagates unchanged.
        raise ToolError(f"failed to fetch attachment: {exc}") from exc


async def _build_files(
    specs: list[dict[str, str]], *, session: aiohttp.ClientSession
) -> list[discord.File]:
    if len(specs) > _MAX_ATTACHMENTS_PER_MESSAGE:
        raise ToolError("max 10 attachments per message")
    files: list[discord.File] = []
    for spec in specs:
        data = await _fetch_attachment(session, spec["url"])
        files.append(discord.File(fp=io.BytesIO(data), filename=spec["filename"]))
    return files


async def _build_files_from_handles(
    filenames: list[str], *, store: FileStore
) -> list[discord.File]:
    """Resolve FileStore filenames into discord.File attachments.

    Lets agents post bytes generated by ``generate_audio`` /
    ``generate_image`` without round-tripping them through https. The
    error string must surface the rejected filename so an agent can fix
    the call without inspecting structured tool output.
    """
    if len(filenames) > _MAX_ATTACHMENTS_PER_MESSAGE:
        raise ToolError("max 10 attachments per message")
    files: list[discord.File] = []
    for name in filenames:
        try:
            handle = store.get(name)
        except KeyError as exc:
            raise ToolError(
                f"file handle {name!r} not found in file store — "
                f"generate it first or check the filename"
            ) from exc
        files.append(discord.File(fp=io.BytesIO(handle.data), filename=handle.display_filename))
    return files


async def _send_message_impl(  # pyright: ignore[reportUnusedFunction]
    runtime: McpRuntime,
    auth: AuthIdentity,
    *,
    channel_id: str,
    content: str,
    attachments: list[dict[str, str]] | None = None,
    file_handles: list[str] | None = None,
    session: aiohttp.ClientSession | None = None,
) -> MessageRow:
    _require_discord_identity(auth)
    guild_id = _require_guild_id(auth)
    token = _require_bot_token(runtime)

    total_attachments = (len(attachments) if attachments else 0) + (
        len(file_handles) if file_handles else 0
    )
    if total_attachments > _MAX_ATTACHMENTS_PER_MESSAGE:
        raise ToolError("max 10 attachments per message")

    files: list[discord.File] = []
    if attachments:
        if session is not None:
            files.extend(await _build_files(attachments, session=session))
        else:
            async with aiohttp.ClientSession() as http_session:
                files.extend(await _build_files(attachments, session=http_session))
    if file_handles:
        if runtime.file_store is None:
            raise ToolError(
                "file_handles requires the media file store to be configured "
                "(set DAIMON_GEMINI__API_KEY on the mcp process)"
            )
        files.extend(await _build_files_from_handles(file_handles, store=runtime.file_store))

    async with rest_client(token) as c:
        _, member = await _resolve_member(c, guild_id, _require_discord_identity(auth))
        raw_channel = await _resolve_channel(c, channel_id)
        channel = _require_guild_channel(raw_channel, guild_id)
        if isinstance(channel, discord.Thread):
            # Thread.permissions_for needs the parent in the guild cache;
            # the per-call REST client starts with an empty one.
            await _ensure_thread_parent_cached(channel)
        _check_send_permission(channel, member)
        if not isinstance(channel, discord.abc.Messageable):
            raise ToolError("channel does not support sending messages")
        sent = await channel.send(content=content, files=files)
        return _to_message_row(sent)
